DFE-Digital/login.dfe.services

azure/parameters.json
azure/template.json

Added ARM template
Added ARM parameters

Added Azure infrastructure

---

Procfile

NSA-887 - split portal

---

.idea/codeStyles/codeStyleConfig.xml
src/app/home/home.js

service_home added to link to service endpoints

NSA-1587- added link to service endpoint

---

package-lock.json
package.json
src/app/home/home.js
src/app/home/views/home.ejs
src/app/layouts/layout.ejs
src/app/organisations/index.js
src/app/organisations/organisations.js
src/app/organisations/views/organisations.ejs
src/routes.js
test/unit/app/home/home.test.js

updated the ui for the services dashboard page

NSA-1624- Services UI update

---

src/app/organisations/views/organisations.ejs

NSA-1624 Org UI update

---

package-lock.json
package.json
src/infrastructure/oidc/index.js

wrap the Issuer.discover with the asyncRetry and apiStrategy

add the new asyncRetry module

---

package-lock.json
src/app/home/home.js
src/app/home/index.js
src/app/home/views/externalServices.ejs
src/app/home/views/home.ejs
src/app/layouts/layout.ejs
src/app/organisations/views/organisations.ejs
src/app/signOut/complete.js
src/app/signOut/views/complete.ejs
src/infrastructure/applications/api.js
src/infrastructure/applications/static.js
test/integration/home/home.routes.spec.js
test/unit/app/home/home.test.js
test/utils/jestMocks.js

Redirect to the external services page if a user is not authenticated, if they are then redirect to internal services page.

Nsa 1756 pre login services

---

src/app/errors/views/notFound.ejs
src/routes.js

NSA-865- render 404 view

---

src/app/layouts/layout.ejs

Added missing divs to display correct banner styling

NSA-1807- added missing banner styling

---

src/app/accessRequests/accessRequests.js
src/app/accessRequests/index.js
src/routes.js

Commented out access request routes as not currently required

Remove access requests routes

---

src/app/users/selectOrganisation.js
src/app/users/views/selectOrganisation.ejs
test/unit/app/users/getSelectOrganisation.test.js
test/unit/app/users/postSelectOrganisation.test.js

Filter orgs by roleID to only display roles you are an approver for in the select org page

Nsa 1899 approver select org bug

---

src/app/users/editPermission.js
src/infrastructure/organisations/api.js
src/infrastructure/search/api.js
src/infrastructure/search/static.js
test/unit/app/users/postEditPermission.test.js

Patch the search api with new role when updated

NSA-1897- edit permission level patch

---

src/app/users/confirmNewUser.js
src/infrastructure/organisations/api.js
src/infrastructure/organisations/static.js
test/unit/app/users/postConfirmNewUser.test.js

patch search indexer when adding an existing DSI user to a new org

NSA-1903- approver add org patch

---

src/app/users/index.js

Fix issue causing select org page to be displayed if approver for only one org

NSA-1912- select org bug

---

src/app/users/associateServices.js
test/unit/app/users/getAssociateServices.test.js

Check user has access to org or pass undefined to policy engine

NSA-2215- policy engine service bug

---

src/app/users/associateServices.js
src/app/users/views/associateServices.ejs
src/app/users/views/confirmNewUser.ejs

Allow invitation in the approver flow without selecting a service

Nsa-2207 invite no services

---

src/app/requestOrganisation/selectOrganisation.js
test/unit/app/requestOrganisation/selectOrganisation.post.test.js

- Check if user has an outstanding request
- Check if user already apart of org

Nsa-2362 validate org req

---

package-lock.json
package.json
src/index.js

- update express error handling to latest version

NSA-2495 - cdn

---

src/app/home/getServices.js

Change where the list of services is filtered for aforms role display

NSA-2494- list services bug

---

src/app/users/views/confirmExistingUser.ejs

Updated the content with 
Title: This user has a DfE Sign-in account
Text: Please review these details and select continue to invite this user to <organisationname>

NSA-2171 update user already registered content

---

src/app/layouts/layout.ejs

NSA-2553 Removing GA meta-tag

---

src/app/users/views/editServices.ejs

NSA-2209 Fix for No roles for this service message not displayed

NSA-2209 Fix for No roles for this service message not displayed

---

src/app/accessRequests/rejectOrganisationRequest.js
src/app/accessRequests/views/rejectOrganisationRequest.ejs

NSA-2454 Approver Organisation Request - Share Rejection Reason

NSA-2454 Approver Organisation Request - Share Rejection Reason

---

src/app/accessRequests/getOrganisationRequests.js
src/app/accessRequests/rejectOrganisationRequest.js
src/app/accessRequests/reviewOrganisationRequest.js
src/app/accessRequests/selectOrganisation.js
src/app/users/usersList.js
src/app/users/views/usersList.ejs
test/unit/app/accessRequests/reviewOrganisationRequest.post.test.js
test/unit/app/accessRequests/selectOrganisation.post.test.js

NSA-2363 View Requests link on Users Page (Approver)

NSA-2363 View Requests link on Users Page (Approver)

---

src/app/accessRequests/getOrganisationRequests.js
src/app/users/usersList.js
src/app/users/views/usersList.ejs

NSA-2363 View Requests link on Users Page (Approver) - fix for user list page and adding back link

NSA-2363 View Requests link on Users Page (Approver) - fix for user list page and adding back link

---

src/app/requestOrganisation/review.js
src/infrastructure/organisations/api.js
src/infrastructure/organisations/static.js
test/unit/app/requestOrganisation/review.post.test.js

NSA-2398 Confirm Request Page - Incorrect text for requests to orgs with no approvers

NSA-2398 Confirm Request Page - Incorrect text for requests to orgs with no approvers

---

src/app/home/getServices.js
src/app/home/views/services.ejs
src/app/organisations/organisations.js
src/app/organisations/views/organisations.ejs
src/app/requestOrganisation/selectOrganisation.js
src/app/requestOrganisation/views/search.ejs
src/infrastructure/organisations/api.js
src/infrastructure/organisations/static.js
test/unit/app/home/getServices.test.js

NSA-2388 Self-Registration - Task Tracker - PR for initial contents of Task List changes

NSA-2388-latest

---

src/app/home/getServices.js
src/app/home/views/services.ejs
src/app/organisations/organisations.js
test/utils/jestMocks.js

Task Tracker - Toggle for prod

Task Tracker - Toggle for prod

---

src/app/home/getServices.js
src/app/home/views/services.ejs
src/app/users/selectOrganisation.js

Allow an approver to add services to own account from services page

NSA-2230- allow add services to self

---

src/app/users/views/summaryPartial.ejs

NSA-2650 intermediate issue when object null during back button click

NSA-2650 intermediate issue when object null during back button click

---

database_scripts/002_ RPA_script_prod.sql

NSA-2756 - RPA Script

---

src/app/requestOrganisation/views/review.ejs

now using git flow branch style

Fix for NSA-2625

---

src/app/signOut/signOut.js
src/index.js

Reverts DFE-Digital/login.dfe.services#215

Revert "this should solve the issue - needs testing in a proper env though"

---

package-lock.json
package.json
src/infrastructure/organisations/api.js

Uses the library DAO for patch requests

WIP: 479 - integrates DAO for patch requests

---

src/infrastructure/organisations/api.js

Bug on import (unsure how this made it in, likely copy-paste or merge error?)

Method call not function call semantics

---

package.json
src/infrastructure/organisations/api.js

Get-all DAO integration ticket.

Use DAO api to get userorgrequests

---

src/infrastructure/applications/api.js

Upstream we're not exposing an Applications repo, this call lists services

Import changed in dao

---

package.json
src/routes.js

so that the helper lib can display it on a healthcheck call

pass through version number

---

src/infrastructure/applications/api.js

Already in the release candidate, merging back to develop

Var rename missing

---

package-lock.json
package.json

New version has been created for login.dfe.winston-appinsights.
Service component is updated to use this new npm library.

feature/NSA-4631Version upgrade of login.dfe.winston-appinsights

---

package-lock.json
package.json

Audit transporter npm library version has been upgraded

PR-feature/NSA-4631-Version of audit transporter has been updated

---

src/index.js

Session timeout has been resorted.

PR-feature/NSA-4813-restore session timeout

---

src/app/home/getServices.js
src/app/requestService/approveServiceRequest.js
src/app/requestService/confirmServiceRequest.js
src/app/requestService/index.js
src/app/requestService/rejectServiceRequest.js
src/app/requestService/requestRoles.js
src/app/requestService/requestService.js
src/app/requestService/views/approveServiceRequest.ejs
src/app/requestService/views/confirmServiceRequest.ejs
src/app/requestService/views/rejectServiceRequest.ejs
src/app/requestService/views/requestRoles.ejs
src/app/requestService/views/requestService.ejs
src/app/users/selectOrganisation.js
src/app/users/utils.js
src/infrastructure/helpers/common.js
src/infrastructure/utils/index.js
src/routes.js
test/unit/app/requestService/requestRoles.get.test.js
test/unit/app/requestService/requestService.get.test.js
test/unit/app/users/getSelectServiceWithOrganisation.test.js
test/unit/app/users/postSelectServiceWithOrganisation.test.js

- Fixed failing test cases
- Select a service template and js changes. 
- Select a sub-service template and js changes
- Placeholder templates for review, approve and reject service-request.

Select a service and sub-service flow for end-user

---

src/app/layouts/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-5447

Added "Accessibility statement" link in the footer

---

package-lock.json
package.json
src/app/users/confirmNewUser.js
src/infrastructure/account/DirectoriesApiAccount.js

Jira tickets:
https://dfe-secureaccess.atlassian.net/browse/NSA-6015
https://dfe-secureaccess.atlassian.net/browse/NSA-6291

Feature/NSA-6015 Invite user email updates

---

src/app/users/usersList.js
src/app/users/views/usersList.ejs

-fix for the table in the Manage Users Dashboard to keep the filters when a column is sorted 
Jira: https://dfe-secureaccess.atlassian.net/browse/NSA-5481

NSA-5481 - fixed table sorting in manage users section

---

src/app/users/organisationPermission.js
src/app/users/views/confirmNewUser.ejs

Fix redirection link after selecting organisation permission in invite new user journey 
Jira ticket:
https://dfe-secureaccess.atlassian.net/browse/NSA-6288

feature/NSA-6288 - fixed redirection link after selecting organisation perm

---

src/app/users/views/usersList.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6390

NSA-6390 - added name wrapping for user management list

---

src/app/requestOrganisation/selectOrganisation.js

Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-5306
AC:2

NSA-5306-Update organisation request cancel button and backlink

---

package-lock.json
package.json

Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-6731
Updated login.dfe.validation verison to include the updated list of the blacklisted emails domains.

[NSA-6731] - Updated blacklisted email domains

---

src/app/accessRequests/rejectSubServiceRequest.js
src/app/accessRequests/reviewSubServiceRequest.js
src/app/accessRequests/views/reviewSubServiceRequest.ejs

fixed reject error

---

package-lock.json
package.json

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7018
Updates:
- Bumped DAO version to allow service and sub-service requests with the following statuses Pending/Overdue/ No approver [0, 2, 3]  - to be actioned (approved / rejected)

[NSA-7018] - bumped DAO version

---

src/app/accessRequests/reviewSubServiceRequest.js
src/app/accessRequests/utils.js
src/app/requestService/approveRolesRequest.js
test/unit/app/accessRequests/approveSubServiceRequest.post.test.js
test/unit/app/requestService/approveRolesRequest.post.test.js

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/NSA-7108
**Updates:** 
- Sub-service request approved banner - content updated for both Approver's journeys (email and dashboard) 
- Removed the `console.log` from `src/app/accessRequests/utils.js`
- Updated unit tests related to the banner changes
- Fixed the ESLint errors in `test/unit/app/accessRequests/approveSubServiceRequest.post.test.js`

[NSA-7108] Sub-service changes - approved request banner updates

---

src/app/requestService/views/requestEditRoles.ejs

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/NSA-7145
**Changes:** 
- Added warning message to sub-service change request page

NSA-7145 -Added warning message to sub-service change request page

---

src/app/accessRequests/views/reviewSubServiceRequest.ejs

needs to add the sub-service heading change

changed sub-service review title

---

src/app/requestService/views/approveRolesRequest.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7010
Changes: 
- Content modifications for the sub-service approval page with the approver coming from the email link.

[NSA-7010] Content changes for sub-service request approval

---

src/app/requestService/requestEditRoles.js
src/app/requestService/requestRoles.js
src/app/requestService/views/requestEditRoles.ejs
src/app/requestService/views/requestRoles.ejs
src/app/users/associateRoles.js
src/app/users/editServices.js
src/app/users/selectServiceWithOrganisation.js
src/app/users/utils.js
src/app/users/views/associateRoles.ejs
src/app/users/views/associateRolesRedesigned.ejs
src/app/users/views/editServices.ejs
src/infrastructure/applications/api.js
test/unit/app/users/getEditServices.test.js

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/NSA-7245
**Changes:** 
- wording changes for Approvers/ End Users request services/sub-services journeys to meet ACs
- updates to the rolesRequirement function to cover all the possible cases 
- refactored and removed duplicate code 
- updates to the service list to display only services associated with the visible organisations (**_View and edit services on my account_** page)
- updates to the service list to display only services associated with organisation where the user is Approver for (**_Remove service from my account_** page)

[NSA-7245] Wording updates for request and edit sub-services and services 

---

src/app/users/views/editServices.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7245
Changes:
- content changes for Approvers sub-services edit journey

[NSA-7245] Content updates for approver sub-services changes

---

package-lock.json
package.json
src/app/users/newUserDetails.js

Implementation for: https://dfe-secureaccess.atlassian.net/browse/NSA-7365
- Updates login.dfe.validation to version 1.3.5, which adds additional emails to the email blacklist.

[NSA-7365] Update login.dfe.validation version to v1.3.5

---

src/app/home/views/services.ejs

needed to fix specificity of html element for testing
https://dfe-secureaccess.atlassian.net/browse/NSA-7474

fix front id

---

Docker/Dockerfile
docker-compose.yml
package.json
src/app/home/getServices.js
src/app/home/views/services.ejs

https://dfe-secureaccess.atlassian.net/browse/NSA-7514
setup to display new sub services that will be displayed for 24 hours or until user closes them

work compete

---

src/app/users/usersList.js

Jira ticket: DSI-6532
Changes: updated the search criteria to escape special characters in Azure cognitive search

[DSI-6532]-Updates to users search to escape special characters

---

src/app/accessRequests/views/allRequestsForApproval.ejs
src/app/home/views/services.ejs
src/app/organisations/views/organisations.ejs
src/app/users/views/usersList.ejs

https://dfe-secureaccess.atlassian.net/browse/DSI-6517
added missing design text

added link design

---

src/app/accessRequests/reviewSubServiceRequest.js
src/app/accessRequests/utils.js
src/app/accessRequests/views/reviewSubServiceRequest.ejs

**Jira ticket**: https://dfe-secureaccess.atlassian.net/browse/DSI-6776
**Changes**: fixed issues with the sub-service requests review page

[DSI-6776] - Fix sub-service requests issues

---

src/app/users/associateRoles.js

**Jira ticket:**
https://dfe-secureaccess.atlassian.net/browse/DSI-6773
**Changes:**
Added the missing `return` statements in `associateRoles.js`

[DSI-6773] - Fixed bugs in the associate roles page 

---

.gitignore
src/app/requestService/approveRolesRequest.js
src/app/requestService/confirmEditRolesRequest.js
src/app/requestService/rejectRolesRequest.js
src/app/requestService/requestEditRoles.js
src/app/requestService/requestRoles.js

Applied sort to sub-service selection process.

Applied sorting of roles to sub-services

---

package-lock.json
package.json
src/app/organisations/views/organisations.ejs

This change improves screen reader accessibility for the "Approvers" column by announcing the specific organisation name.  
For example, prior to this change screen readers would announce "Show approvers" where-as now "show approvers for [name of organisation]"

DSI-6820: Fix screen reader accessibility for "show approvers" link.

---

src/app/layouts/layout.ejs

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7050
-    Change the navigation title from 'Services' to 'My services'

[DSI-7050]-Change the navigation title from 'Services' to 'My services'

---

src/app/users/views/usersList.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7126
Removed the important banner from the management console.

[DSI-7126] Remove "Important" Banner

---

package-lock.json
src/app/layouts/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7133
- Navigation title reverted to “Services” as the navigation menu was too wide and displaced to the next line.
- Fix 1 vulnerable package using `npm audit fix` command
https://github.com/DFE-Digital/login.dfe.services/pull/572

[DSI-7133] Navigation menu displaced to the next line

---

src/app/home/getServices.js
src/app/home/views/services.ejs
test/unit/app/home/getServices.test.js

Jira ticket: [DSI-7051](https://dfe-secureaccess.atlassian.net/browse/DSI-7051)
- Added Detail Component.
- Created a function to retrieve all organisations names by service and group them accordingly.
- Services filter updated `lodash/uniqBy` removed.
- Updated test.
- Run Prettier.

[DSI-7051] Add show organisations details to service table

---

package-lock.json
package.json
src/app/home/home.js
src/app/home/views/landingPage.ejs
test/unit/app/home/home.test.js
test/utils/jestMocks.js

Jira ticket: [DSI-7233](https://dfe-secureaccess.atlassian.net/browse/DSI-7233)
- Added Help and Chatbot URLs to the home page.
- Ensured links to the Contact Us and Help Assistant pages work correctly.
- Added help assistant url to hosting environments
- Updated tests to cover new features.
- Improved accessibility by adding aria-live and role attributes to the detail component.
- Fixed one moderate severity vulnerability using `npm audit fix`.
- Ran Prettier for consistent formatting.
- Updated config schema version
- https://github.com/DFE-Digital/login.dfe.dsi-config/pull/20
- https://github.com/DFE-Digital/login.dfe.config.schema.common/pull/35

[DSI-7233] add related actions to the DSI start page

---

package-lock.json
src/app/home/views/services.ejs

Jira ticket: [DSI-7154](https://dfe-secureaccess.atlassian.net/browse/DSI-7154)
- Updated text on the set up account screen.
- Ran Prettier for consistent formatting.
- Fixed two high severity vulnerability using `npm audit fix`.

[DSI-7154] Service text change on the set up account screen

---

package-lock.json
src/app/accessRequests/views/allRequestsForApproval.ejs
src/app/home/views/services.ejs
src/app/organisations/views/organisations.ejs
src/app/users/views/usersList.ejs

Jira ticket: [DSI-6615](https://dfe-secureaccess.atlassian.net/browse/DSI-6615)
- Updated heading text across different pages.
- Fixed three moderate severity vulnerability using `npm audit fix`.
- https://github.com/DFE-Digital/login.dfe.profile/pull/309
- https://github.com/DFE-Digital/login.dfe.manage/pull/262

[DSI-6615] Review page summaries across the DfE Sign-in service - update statement in blue textbox 

---

src/app/requestOrganisation/review.js
src/app/requestOrganisation/views/review.ejs
test/unit/app/requestOrganisation/review.post.test.js

Jira: [DSI-7215](https://dfe-secureaccess.atlassian.net/browse/DSI-7215)
- A reason must be specified when request access to an organisation
- The reason length must be <= 1000 characters
- Change the layout and wording of the page as per the ticket [DSI-7215](https://dfe-secureaccess.atlassian.net/browse/DSI-7215)
- Add additional test cases

[DSI-7215] Improve reason for organisation request

---

src/app/requestOrganisation/views/review.ejs

Jira ticket: [DSI-7269](https://dfe-secureaccess.atlassian.net/browse/DSI-7269)
- Text change on the request organisation review page

[DSI-7268] Reason for organisation request update

---

package-lock.json
package.json

Link to ticket: [NSA-8691](https://dfe-secureaccess.atlassian.net/browse/NSA-8691)
Updated validations version in package.json

[NSA-8691] Update DfE package versions

---

package-lock.json
src/app/users/views/confirmNewUser.ejs

Jira: https://dfe-secureaccess.atlassian.net/browse/DSI-7412
- Added the class property `prevent-form-double-submission` to the html form, thus preventing double clicks
- Fixed 2 moderate npm vulnerabilities with `npm audit fix`

[DSI-7412] Prevent double click when submitting a user invitation

---

src/app/accessRequests/reviewSubServiceRequest.js
src/app/accessRequests/utils.js
src/app/users/editServices.js
src/app/users/utils.js

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7400
- fix Cancel button redirect link for Select a sub-service (editing services as an approver) and Review sub-service request pages

[DSI-7400]fix cancel link redirect

---

src/app/users/editServices.js
test/unit/app/users/getEditServices.test.js

Jira ticket: [DSI-7462](https://dfe-secureaccess.atlassian.net/browse/DSI-7462)
- Fix Back button link for Select a sub-service (editing services in account) and Review sub-service request pages

[DSI-7462] Align sub service request pages for approvers

---

src/app/accessRequests/getAllRequestsForApproval.js
src/app/helpers/durationFormatterHelper.js
src/app/home/home.js
src/app/home/views/landingPage.ejs
test/unit/app/helpers/dateFormatterHelper.test.js
test/unit/app/helpers/durationFormatterHelper.test.js
test/unit/app/home/home.test.js

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7465
- use momentjs to format cookie timeout text
- update service homepage to include revised cookie wording
- add test cases for the above
- updated existing tests
- prettier formatting

[DSI-7465] Format session inactivity label

---

src/app/requestOrganisation/review.js
src/app/requestOrganisation/views/review.ejs
test/unit/app/requestOrganisation/review.post.test.js

Jira ticket: [DSI-7598](https://dfe-secureaccess.atlassian.net/browse/DSI-7598)
- Added placeholder text.
- Updated text content.
- Implemented the Character Count GDS kit component.
- Updated test.

[DSI-7598]  Reason for request content changes

---

src/index.js

Resolve config output

---

package-lock.json
package.json

Ticket: [NSA-9266](https://dfe-secureaccess.atlassian.net/browse/NSA-9266)
- Updating Validation package

[NSA-9266] Update dfe package version
